<?php
namespace DevNoKage\Enums;

enum ClassName: string {
    case APP = "APP";
    case DATABASE = "DATABASE";
    case ERROR_CONTROLLER = "ERROR_CONTROLLER";
    case ROUTER = "ROUTER";
    case SETTER_GETTER = "SETTER_GETTER";
    case SINGLETON = "SINGLETON";
    
    case COMPTEUR_REPOSITORY = "COMPTEUR_REPOSITORY";
    case LOG_REPOSITORY = "LOG_REPOSITORY";
    case ACHAT_REPOSITORY = "ACHAT_REPOSITORY";
    case TRANCHE_REPOSITORY = "TRANCHE_REPOSITORY";

    case COMPTEUR_SERVICE = "COMPTEUR_SERVICE";
    case LOG_SERVICE = "LOG_SERVICE";
    case ACHAT_SERVICE = "ACHAT_SERVICE";
    case TRANCHE_SERVICE = "TRANCHE_SERVICE";

    case COMPTEUR_CONTROLLER = "COMPTEUR_CONTROLLER";
    case ACHAT_CONTROLLER = "ACHAT_CONTROLLER";

    case ACHAT = "ACHAT";
    case CLIENT = "CLIENT";
    case COMPTEUR = "COMPTEUR";
    case LOG = "LOG";
    case TRANCHE = "TRANCHE";
    case RESPONSE = "RESPONSE";
}
